title: JKAN
description: A lightweight, backend-free open data portal, powered by Jekyll
baseurl: "/jkan"

navigation:
  - title: Datasets
    url: /datasets/
  - title: Organizations
    url: /organizations/
  - title: Categories
    url: /categories/

collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: false
  categories:
    output: false

defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization
  - scope:
      path: ""
      type: categories
    values:
      layout: category

prose:
  siteurl: 'http://timwis.com/jkan'
  metadata:
    _datasets:
      - name: title
        field:
          element: text
          label: Title
      - name: organization
        field:
          element: text
          label: Organization
      - name: notes
        field:
          element: textarea
          label: Description
      - name: maintainer
        field:
          element: text
          label: Maintainer
      - name: maintainer_email
        field:
          element: text
          type: email
          label: Maintainer Email
  ignore:
    - search.json
    - .gitignore
    - .travis.yml
    - deploy.sh
    - Gemfile
    - Gemfile.lock
    - LICENSE

gems:
  - octopress-paginate

pagination:
  permalink: /page-:num/

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
