# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Title
    datajson: title
  - field_name: organization
    label: Organization
    form_template: form/organization.html
    datajson: publisher.name
  - field_name: notes
    label: Description
    form_template: form/textarea.html
    datajson: description
  - field_name: license_url
    label: License URL
    form_template: form/license.html
    datajson: license.url
    values:
      - name: Creative Commons Attribution
        url: https://creativecommons.org/licenses/by/4.0/
      - name: Creative Commons Attribution Share-Alike
        url: https://creativecommons.org/licenses/by-sa/4.0/
      - name: Creative Commons CCZero
        url: https://creativecommons.org/publicdomain/zero/1.0/
      - name: UK Open Government Licence
        url: https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
      - name: Open Data Commons Attribution License
        url: http://www.opendefinition.org/licenses/odc-by
      - name: Open Data Commons Open Database License (ODbL)
        url: http://www.opendefinition.org/licenses/odc-odbl
      - name: Open Data Commons Public Domain Dedication and Licence (PDDL)
        url: http://www.opendefinition.org/licenses/odc-pddl
      - name: Not Applicable
        url: ''
      - name: Other...
        url: 'other'
  - field_name: license_name
    label: License Name
    datajson: license.name
    form_template: form/hidden.html
  - field_name: category
    label: Category
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: maintainer
    label: Maintainer
    datajson: contactPoint.fn
  - field_name: maintainer_email
    label: Maintainer Email
    datajson: contactPoint.hasEmail

resource_fields:
  - field_name: name
    label: Resource Name
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.downloadURL
  - field_name: format
    label: Format
    datajson: distribution.format
    form_template: form/dropdown.html
    values:
      - api
      - csv
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml

organization_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html
